 
name: LitmusDocs-CI
on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  embedmd:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          ref: ${{steps.getcommit.outputs.sha}} 

      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.14.0'

      - name: Installing and Running embedmed
        run: |
          go get github.com/campoy/embedmd
          cd docs
          embedmd -w $(find *.md)
        continue-on-error: true  
        
      - name: embedmd check
        run: |
          border()
          {
              title="| $1 |"
              edge=$(echo "$title" | sed 's/./-/g')
              echo "$edge"
              echo "$title"
              echo "$edge"
          }
          export TERM=xterm-256color 
          count=$(git status -s| wc -l)
          if [ "$count" -ne "0" ]
          then
            tput setaf 1; echo "embedmd check failed!!!"
            tput setaf 4; echo "Please check these files need a run embedmd run:"
            output=$(git status -s)
            border "$output"
            echo "Please follow the instructions to run embedmd:"
            echo "cd docs\nembedmd -w $(find *.md)"
            echo "For more info visit https://github.com/litmuschaos/litmus-docs/blob/master/CONTRIBUTING.md"
            exit 1
          else
            echo "Nothing to embed"
          fi
        shell: sh
