 
name: LitmusDocs-CI
on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  embedmd:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
        with:
          ref: ${{steps.getcommit.outputs.sha}}      

      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.14.0'

      - name: Installing and Running embedmed
        run: |
          go get github.com/campoy/embedmd
          cd docs
          embedmd -w $(find *.md)
        continue-on-error: true  
        
      - name: embedmd check
        run: |
          count=$(git status -s)
          if [ "$count" -ne "0" ]
          then
            echo "embedmd check failed\nThese files need to run embedmd once:"
            git status -s
            echo "Please follow the instructions to run embedmd:"
            echo "cd docs\nembedmd -w $(find *.md)"
            echo "For more info visit https://github.com/litmuschaos/litmus-docs/blob/master/CONTRIBUTING.md"
            exit 1
          else
            echo "Nothing to embed"
          fi
        shell: sh
